web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  container_name: web

php:
  build: .
  volumes: 
    - ./code:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    - maildev
  container_name: php

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password
  container_name: mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB
  container_name: phpmyadmin

maildev:
  image: djfarrelly/maildev
  ports:
   - "8081:80"
  container_name: maildev
